Set R_GC_MEM_GROW=3 globally for all tasks.
mrc-ide/hipercow pull request #125
Opened 2024-05-23 16:28 UTC by plietar

We've found that setting this value provides significant speedup for some of our workloads. The downside is a slight increase in memory consumption, but our jobs are not usually memory bound anyway.

This can still be overriden, either by setting the `hipercow.default_envvars` option, or by assigning a specific value on individual tasks.

2024-05-23 16:31 UTC, plietar commented
Here are some rough benchmarks on malariasimulation, for a population size of 1M and 1000 time steps: [plot.pdf](https://github.com/mrc-ide/hipercow/files/15419749/plot.pdf)

It's not really clear why `R_GC_MEM_GROW=0` is also beneficial, but it feels to me like a dangerous road to pick.

2024-05-23 17:24 UTC, richfitz requested changes
Can you add a section to the details vignette on this please? https://mrc-ide.github.io/hipercow/articles/details.html

2024-05-23 17:24 UTC, richfitz commented on R/envvars.R
> +  ret <- ret[!duplicated(ret$name, fromLast=TRUE),]
```suggestion
  ret <- ret[!duplicated(ret$name, fromLast = TRUE), ]
```

2024-05-23 17:24 UTC, richfitz commented on tests/testthat/test-envvars.R
> +  e3 <- hipercow_envvars(A = "2", secret=TRUE)
```suggestion
  e3 <- hipercow_envvars(A = "2", secret = TRUE)
```

2024-05-23 17:24 UTC, richfitz commented on R/zzz.R
> +DEFAULT_ENVVARS <- hipercow_envvars(R_GC_MEM_GROW = "3")
```suggestion
DEFAULT_ENVVARS <- hipercow_envvars("R_GC_MEM_GROW" = "3")
```

2024-05-31 13:28 UTC, richfitz commented on R/zzz.R
> +DEFAULT_ENVVARS <- hipercow_envvars("R_GC_MEM_GROW" = "3")
```suggestion
DEFAULT_ENVVARS <- hipercow_envvars("R_GC_MEM_GROW" = "3") # nolint
```

2024-05-31 14:17 UTC, plietar commented
> Can you add a section to the details vignette on this please? https://mrc-ide.github.io/hipercow/articles/details.html

Done.

2024-06-03 12:29 UTC, richfitz approved these changes

2024-06-03 12:38 UTC, merged